import {
  ADD_CARD,
  ADD_COLUMN,
  EDIT_COLUMN_TITLE,
  REORDER_CARD,
  REORDER_LIST,
  SET_CURRENT_BOARD_LISTS,
} from "../actions/actionTypes";

const initialState = {
  columns: null,
  columnOrder: null,
};

const listReducer = (state = initialState, action) => {
  switch (action.type) {
    case REORDER_CARD: {
      const { newSameColumnList, newDifferentColumnsList } = action.payload;

      if (newSameColumnList) {
        const newState = {
          ...state,
          columns: {
            ...state.columns,

            [newSameColumnList.id]: newSameColumnList,
          },
        };

        return newState;
      }

      if (newDifferentColumnsList) {
        const newState = {
          ...state,
          columns: {
            ...state.columns,
            ...newDifferentColumnsList,
          },
        };
        console.log(newState);

        return newState;
      }
    }
    break;

    case REORDER_LIST: {
      const newColumnOrder = action.payload;

      const newState = {
        ...state,
        columnOrder: newColumnOrder,
      };
      return newState;
    }

    case SET_CURRENT_BOARD_LISTS: {
      const { columns, columnOrder } = action.payload;
      const newColumnOrder = columnOrder;
      const newColumns = columns.reduce((accum, currentValue, currentIndex) => {
        accum[currentValue._id] = {
          title: currentValue.title,
          id: currentValue._id,
          cardIds: currentValue.cardIds,
        };

        return accum;
      }, {});

      const newState = {
        ...state,
        columns: newColumns,
        columnOrder: newColumnOrder,
      };

      return newState;
    }

    case EDIT_COLUMN_TITLE: {
      const { editedTitle, columnId } = action.payload;
      const editedColumn = {
        [state.columns[columnId]]: {
          ...state.columns[columnId],
          content: editedTitle,
        },
      };
      const newState = {
        ...state,
        columns: {
          ...state.columns,
          editedColumn,
        },
      };
      return newState;
    }

    case ADD_COLUMN: {
      const { title, cardIds, columnId } = action.payload;

      if (title && cardIds && columnId) {
        const newColumn = {
          title,
          cardIds,
          id: columnId /* here i am assigning id propert with columnId generated by uuid from listActions*/,
        };

        return {
          ...state,
          columns: {
            ...state.columns,

            [columnId]: newColumn,
          },
          columnOrder: state.columnOrder.concat(columnId),
        };
      }
    }
    break;

    case ADD_CARD: {
      const { columnId, cardId } = action.payload;
      return {
        ...state,
        columns: {
          ...state.columns,
          [columnId]: {
            ...state.columns[columnId],
            cardIds: state.columns[columnId].cardIds.concat(cardId),
          },
        },
      };
    }

    default:
      return state;
  }
};

export default listReducer;
